manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cb00077  # Last-known-good as of 2025-06-02; main moved to Zephyr HWMv2 and broke this config
      import: app/west.yml
  self:
    path: config
